### ISSUE TITLE
Is it possible to port to android

### ISSUE THREAD

**Issue by Enderlais** [adithya-s-sekhar/advanced-youtube-client-ayc#1]
I wanted to k now itf it is possible to port this program to android because if that would be possible I would like to do that or I would like to have an android version.

**Comment by Enderlais** [comment]
well that was fast thank you a lot i think i will try out your version first i just really love all the options but i guess its dead 
thank you a lot the program is awsome and i hope at some point i can use it on ios and android too

**Comment by adithya-s-sekhar** [comment]
@Enderlais I tried fixing my personal script for everyone to use, maybe this could be what you're looking for

https://github.com/adithya-s-sekhar/termux-setup

**Comment by Enderlais** [comment]
@adithya-s-sekhar so what doo i have to doo now do i have to download the application from the normal steps so the lastest realease (7 January 2022)?

**Comment by adithya-s-sekhar** [comment]
Yes, right now it only downloads all videos in the highest quality.
