### ISSUE TITLE
Keeps saying "Download Failed" with any YouTube video.

### ISSUE THREAD

**Issue by SatinFoil** [adithya-s-sekhar/advanced-youtube-client-ayc#4]
```
------------------------------------------------------------
                Advanced Youtube Client - AYC

                     v4.5 (04/Jul/2023)
------------------------------------------------------------

 Download Failed!!!! :-(

 URL: (Any YouTube video link)

 Possible problems and solutions:

 - yt-dlp might be out of date. Update it by going
   into Settings, Update yt-dlp.
 - If you have an unreliable network, increase retry
   attempts in Settings.
 - You may have entered an invalid/private link. These
   aren't supported yet.

  If all else fails, report the failing URLs on the
  Sourceforge or GitHub page.

------------------------------

 Press enter to close this window.
```
I just installed and set it up and this keeps happening. My settings are MP4, 1080p60, but it seems to happen on other quality settings as well.

**Comment by adithya-s-sekhar** [comment]
Can you share one of these urls that's failing? Also what was the last thing shown on screen before the error page?

**Comment by SatinFoil** [comment]
> Can you share one of these urls that's failing? Also what was the last thing shown on screen before the error page?

Hello! I already fixed it, but forgot to close this. Turns out it was because I was using rehike, so I just temporarily disable it when using this.
