### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by iruzer** [adithya-s-sekhar/advanced-youtube-client-ayc#5]
hello

how to add cookies.txt when downloading video from bilibili for premium features ?

**Comment by adithya-s-sekhar** [comment]
Still testing ways to do this in v4.7 but you can try it now with [this test build](https://drive.google.com/drive/folders/1h-OZPAYxQN-ByAr715u2kCywVGcxxjxN?usp=drive_link).

There are two ways to load cookies.txt in the above build
1. Just copy cookies.txt to ayc folder, it'll auto detect it and use it for ALL downloads not just bilibili.
2. Or in AYClient.bat [line 12](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/main/AYClient.bat#L12) you can add a `--cookies path_to_cookie` line for just non-youtube downloads.

If anything breaks let me know.

**Comment by iruzer** [comment]
I am already download it but it stil said 4.6

**Comment by adithya-s-sekhar** [comment]
The version number isn't changed because it's a test build. You have to put cookies.txt in the same folder as ayclient.bat and then start ayclient. It'll show cookies.txt loaded.

**Comment by iruzer** [comment]
it success to download 1080p on bilibili
![cmd_SQuraPFp2s](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/assets/6658676/12879bf3-2645-4891-97c6-1ba10681d533)
but it don't detect 720p or 1080 when i choose quality
![cmd_J39rfSLjJD](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/assets/6658676/04328e74-e9b4-4e07-af61-fd2e63b90d39)

**Comment by adithya-s-sekhar** [comment]
This should fix it. No need to reinstall, just copy and replace the **scripts folder** and **AYClient.bat** file from this. 

[ayc-test-20230804-1541.zip](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/files/12259667/ayc-test-20230804-1541.zip)

**Comment by iruzer** [comment]
it is work

![cmd_TcwJZPLj0c](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/assets/6658676/d71e1061-0934-4bed-8832-ff6f1b6f0570)

thank you very much.
For true premium, i will test it again when i am ready to apply it

**Comment by adithya-s-sekhar** [comment]
Happy to hear that. I'll close this issue when this feature is released for everyone.

**Comment by adithya-s-sekhar** [comment]
Fixed in [v4.7](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/releases/tag/v4.7).
