### ISSUE TITLE
how do i keep the playlist order when downloading one

### ISSUE THREAD

**Issue by Enderlais** [adithya-s-sekhar/advanced-youtube-client-ayc#6]
can you tell me how i can keep the order of my play list when downloading it (like numbering them in the front eg: 001 002 003.... and then the name and so on behind it)
(i tried to do it with the faq but i couldn't)
thank you

**Comment by adithya-s-sekhar** [comment]
Filenames are hardcoded at the moment, I will make it easier to change in the future and also add this as an option.

For now, you need to add `%%(playlist_index)s` to the front of the filename in **resources\scripts\downloader\youtube.bat** (assuming it's for youtube), at line [273](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/main/resources/scripts/downloader/youtube.bat#L273).

Like this:

Now it looks like this

> if %format_chosen% == h264 %youtube_dl% %default_config% %conf% %aria2% %subs% %thumbs% -P home:"%loc%" -o "%%(title).177s-MP4-%%(height).4sp-%%(id).12s.%%(ext)s" %custom_config_youtube% %cookies% "%url%" && set youtube_download_status=1 & goto :EOF

Change it to 

> if %format_chosen% == h264 %youtube_dl% %default_config% %conf% %aria2% %subs% %thumbs% -P home:"%loc%" -o "**%%(playlist_index)s** %%(title).177s-MP4-%%(height).4sp-%%(id).12s.%%(ext)s" %custom_config_youtube% %cookies% "%url%" && set youtube_download_status=1 & goto :EOF

This will download all files as 1 xxx.mp4, 2 xxx.mp4...12 xxx.mp4. You can add a '-' between %%(playlist_index)s and %%(title)s if you want hyphens between them.

Also note line 273 is for h264 videos only. VP9 is line [274](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/ae479678959a693927525ff074b75426d6613421/resources/scripts/downloader/youtube.bat#L274), AV1 is line [275](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/ae479678959a693927525ff074b75426d6613421/resources/scripts/downloader/youtube.bat#L275), M4A is [276](https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/blob/ae479678959a693927525ff074b75426d6613421/resources/scripts/downloader/youtube.bat#L276) and so on.

I know this is a bit complicated, if you have any doubts feel free to ask :) I'll put playlist numbering in a test build soon.

**Comment by Enderlais** [comment]
it worked, thank you
