### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [adithya-s-sekhar/advanced-youtube-client-ayc#7]
Does this work with Win 7?

Thanks

**Comment by adithya-s-sekhar** [comment]
It should on Win 7 SP1.

**Comment by sonuspk** [comment]
please send window 7 download link

**Comment by adithya-s-sekhar** [comment]
@sonuspk try this https://github.com/adithya-s-sekhar/advanced-youtube-client-ayc/releases/download/v4.22/ayc-v4.22-win32.zip

**Comment by adithya-s-sekhar** [comment]
Closed for inactivity and hopefully everything's fixed.
